### PR TITLE
#56 - globalize exception handling

### LINKED ISSUE #56: Use Exception Handler for all Listeners and all Implementations

### PR DESCRIPTION
**Pull request by mykola-digtiar**
Closes #56.

The `ProgramException` throws were replaced with calls of `ExceptionHandler.handleException` method. The only problem is that the ExceptionHandler object is not Singleton and therefore the `exitOnException` condition will only work for exceptions handled by the ExceptionHandler object that is stored in `ProgramState`.

Because there are no exceptions thrown, additional return statements and logic were introduced to make sure that the program will run with exceptions until the end.

[Tests](https://elf-ci.rohrschacht.de/job/BLF/330) seem to be fine.

### CODE REVIEW

**Comment by mykola-digtiar** [comment]
Seems like new tests do not pass anymore, will try to investigate.

File: src/main/java/blf/core/writers/XesWriter.java [hunk 1]
```diff
@@ -174,38 +161,32 @@ public void addStringList(@NonNull String key, @NonNull List<String> values) {
     }
 
     @Override
-    protected void writeState(String filenameSuffix) throws Throwable {
+    protected void writeState(String fileNameSuffix) {
```
Comment (rohrschacht) [inline src/main/java/blf/core/writers/XesWriter.java:164]: Unfortunately, your logic changes in this function were what we had to change for the streaming mode and the safe batching mode to work. I believe that you have to revert them in order for them to work again.

File: src/main/java/blf/core/writers/XesWriter.java [hunk 2]
```diff
@@ -174,38 +161,32 @@ public void addStringList(@NonNull String key, @NonNull List<String> values) {
...
-        // Before
-        Map<String, Map<String, XTrace>> formerTraces = deepCopyTraces();
-        Map<String, Map<String, Map<String, XEvent>>> formerEvents = deepCopyEvents();
-        // Modification of state
         final Map<String, XLog> logs = this.getLogs();
-        // Restore of state
-        this.traces.clear();
-        this.events.clear();
-        this.traces.putAll(formerTraces);
-        this.events.putAll(formerEvents);
```
Comment (rohrschacht) [inline src/main/java/blf/core/writers/XesWriter.java:188]: Without this storing and retrieving of the former state, the safe batching mode will fail. This is because getLogs() modifies XesWriters state.
In both streaming and safe batching mode, this function writeState() gets called multiple times. But getLogs() modifies the state in a way which assumes that it is only called once at the very end of the extraction.
It may not be pretty, but without it, safe batching at least will not produce the same result as default batching!

File: src/main/java/blf/core/writers/XesWriter.java [hunk 3]
```diff
@@ -174,38 +161,32 @@ public void addStringList(@NonNull String key, @NonNull List<String> values) {
...
-            LOGGER.info("Xes export finished unsuccessfully.");
-            final String message = "Error exporting data to XES.";
-            throw new ProgramException(message, t);
+        } catch (Exception e) {
+            final String errorMsg = "Error exporting data to XES.";
+            this.exceptionHandler.handleException(errorMsg, e);
+        } finally {
+            this.events.clear();
+            this.traces.clear();
+            this.element = null;
```
Comment (rohrschacht) [inline src/main/java/blf/core/writers/XesWriter.java]: The problem with clearing the state in finally is the following: writeState() is called multiple times in the new modes. But in safe batching mode, the state must not be cleared after the write. Otherwise we lose information in the output file.

**Review by rohrschacht — CHANGES_REQUESTED** [review]
You somehow reverted our changes in the XesWriter.writeState() function, which breaks streaming and safe batching mode.

File: src/main/java/blf/core/writers/LogWriter.java [hunk 4]
```diff
@@ -26,22 +32,37 @@ public void addLogLine(@NonNull List<Object> itemParts) {
...
+
+            for (String line : lines) {
+                logBufferedWriter.write(line);
+                logBufferedWriter.newLine();
             }
+
+        } catch (Exception e) {
+            this.exceptionHandler.handleException(logLineWriteErrorMsg, e);
+        } finally {
+            this.lines.clear();
```
Comment (rohrschacht) [inline src/main/java/blf/core/writers/LogWriter.java]: I believe this causes a problem in safe batching mode as well. State should not be unconditionally cleared after every write. The deletion of the state should be handled by the abstract DataWriter class, dependend on the emission mode.

File: src/main/java/blf/core/writers/CsvWriter.java [hunk 5]
```diff
@@ -90,29 +93,62 @@ protected void deleteState() throws Throwable {
...
+
+        } catch (Exception e) {
+            this.exceptionHandler.handleException(exportErrorMsg, e);
         } finally {
-            LOGGER.info(String.format("Export of CSV table %s finished.", tableName));
+            LOGGER.info(exportFinishInfoMsg);
+
+            this.tables.remove(tableName);
+            this.rowCounts.remove(tableName);
+            this.columnNames.remove(tableName);
```
Comment (rohrschacht) [inline src/main/java/blf/core/writers/CsvWriter.java]: Same problem will probably arise here. In safe batching mode, writeState() and then writeTable() will be called multiple times, but state has to be preserved between them.

**Review by rohrschacht — CHANGES_REQUESTED** [review]
The same problem with the finally in the XesWriter is in the CsvWriter and the LogWriter as well, unfortunately. It is probably enough to just remove the state clearing from the finallys.

File: src/main/java/blf/core/writers/XesWriter.java (hunk 3 above)
Comment (mykola-digtiar) [reply src/main/java/blf/core/writers/XesWriter.java]: Removed

**Review by rohrschacht — APPROVED** [review]
Now that the Jenkins tests all pass, I can finally approve this PR.
So. Much. Work. Again! Amazing Job.
It will feel so good to cross this off our list! :+1:

**Review by PaulsBecks — APPROVED** [review]

**Comment by PaulsBecks** [comment]
Good job @Neckster, huge amount of code you had to change here. 👍
